apiVersion: apps/v1
kind: Deployment
metadata:
  name: od-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: od
      version: v2
  template:
    metadata:
      labels:
        app: od
        env: canary
    spec:
      containers:
        # Here is the image of the container
        - name: od
          image: gcr.io/instructor-partition/od-maskrcnn
          imagePullPolicy: Always
          args:
            - "-text=version:v2"
            - -listen=:8080
          imagePullPolicy: Always
          name: od-v1
          ports:
            - containerPort: 8080
